taco:
  orders:
    pageSize: 10

#server:
#  port: 9090
#  ssl:
#    key-store: file:///path/to/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

#spring:
#  datasource:
#  url: jdbc:mysql://localhost/example
#  username: root
#  password: 1234
#  driver-class-name: com.mysql.jdbc.Driver
#  schema:
#    - order-schema.sql
#    - ingredient-schema.sql
#    - taco-schema.sql
#    - user-schema.sql
#    data:
#      - ingredients.sql
#  datasource:
#    jndi-name: java:/comp/env/jdbc/tacoCloudDS
#  logging:
#  path: /var/logs/
#    file: TacoCloud.log
#    level:
#    root: WARN
#    org:
#    org.springframework.security: DEBUG

#greeting:
#  welcome: You are using ${spring.application.name}

#logging:
#  level:
#    tacos: DEBUG


#spring:
#  profiles:
#    active:
#      - prod
#      - audit
#      - ha


#logging:
#  level:
#  tacos: DEBUG
#---
#spring:
#  profiles: prod
#  datasource:
#  url: jdbc:mysql://localhost/example
#  username: root
#  password: 1234
#logging:
#  level:
#  tacos: WARN